"""Initial Migration

Revision ID: d27da91c3674
Revises: 
Create Date: 2021-06-23 15:30:05.588167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27da91c3674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=12255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_institution'), 'course', ['institution'], unique=False)
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_index(op.f('ix_course_institution'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
